<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Install\Module'                        => __DIR__ . '/Module.php',
    'Install\Controller\IndexController' => __DIR__ . '/src/Install/Controller/IndexController.php',
    'InstallTest\Framework\TestCase'        => __DIR__ . '/tests/Install/Framework/TestCase.php',
    'InstallTest\SampleTest'                => __DIR__ . '/tests/Install/SampleTest.php',
);
